######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 23 18:44:03 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    scene.cpp

HEADERS += \
    scene.h
